spring:
  profiles:
    group:
      local: localDB, devPort
      dev: devDB, devPort

  data:
    redis:
      host: localhost
      port: 6379

---

spring:
  config:
    activate:
      on-profile: localDB

  datasource:
    url: ${DATASOURCE_URL}?serverTimezone=Asia/Seoul
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      validation-query: select 1

  sql:
    init:
      platform: mysql

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

---

spring:
  config:
    activate:
      on-profile: devDB

  datasource:
    url: ${DATASOURCE_URL_DEV}?serverTimezone=Asia/Seoul
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      validation-query: select 1

  sql:
    init:
      platform: mysql

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

---

spring:
  config:
    activate:
      on-profile: devPort

server:
  port: 8081
  servlet:
    context-path: /api

---

cloud:
  aws:
    s3:
      bucket: your-bucket-name
    region:
      static: ap-northeast-2
